
package com.javanbeyond.binaryadditionservice;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source
 * version: 2.2
 * 
 */
@WebService(portName = "BinaryAdditionServiceSOAP", serviceName = "BinaryAdditionService", targetNamespace = "http://www.javanbeyond.com/BinaryAdditionService/", wsdlLocation = "WEB-INF/wsdl", endpointInterface = "com.javanbeyond.binaryadditionservice.BinaryAdditionService")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class BinaryAdditionService_BinaryAdditionServiceSOAPImpl
		implements BinaryAdditionService {

	public BinaryAdditionService_BinaryAdditionServiceSOAPImpl() {
	}

	/**
	 * 
	 * @param parameters
	 * @return returns com.javanbeyond.binaryadditionservice.BinaryAddResponse
	 */
	public BinaryAddResponse binaryAdd(BinaryAddRequest parameters) {

		try {
			// Create a Object Factory method for this package to create
			// equivalent java objects for this
			// namespace/package
			ObjectFactory objFactory = new ObjectFactory();
			BinaryAddResponse _return = objFactory.createBinaryAddResponse();
			Thread.sleep(5000);
			_return.setOut(Integer
					.toBinaryString(Integer.parseInt(parameters.getA(), 2)
							+ Integer.parseInt(parameters.getB(), 2)));
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
